### ISSUE TITLE
ERROR: This error happened during the backup: Medusa only supports one data directory

### ISSUE THREAD

**Issue by piotrrybicki** [thelastpickle/cassandra-medusa#40]
It seems, medusa does not support C* nodes with more than 1 data directory.
I believe, that it would be very usefull, to mention this in DOCs.

Are there any plans to support it in the future ? ;-)

BTW. It seems to be excellent tool for backup & restore . Lightweight (as opposed to priam or cassy), and having good foundaion (no JAVA !).

But I can't use it right now :(

Best regards
Piotr Rybicki

**Comment by adejanovski** [comment]
Hi @piotrrybicki,

I agree we should mention it in the docs and it is a known limitation of Medusa.
We have no plans to support multiple directories but would happily accept a contribution ;)

**Comment by lenindv** [comment]
am getting this error though I provided only one data directory, pls help me in this regard

data_file_directories: /opt/cassandra/data

**Comment by adejanovski** [comment]
Hi @lenindv,

I think the problem is that in Medusa, we're expecting an array (or a list). Something like this in the yaml:
```
 data_file_directories:
     - /var/lib/cassandra/data
```

And you made it a string. So when we test for the length of the value we're parsing, we get a number higher than 1 since we're dealing with a string, not an array :

https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/cassandra_utils.py#L211-L217 

We need to figure out how to distinguish both cases by testing the type of the value returned by the yaml parser.

**Comment by lenindv** [comment]
Thanks @adejanovski changed my Yaml accordingly, now it is resolved

**Comment by lenindv** [comment]
Hi @adejanovski ,

now am facing error on a different issue, can you pls help me in this regard 

 This error happened during the backup: expected '<document start>', but found '<block mapping start>'
  in "/opt/cassandra/conf/cassandra.yaml", line 25, column 1

am getting error at num_tokens : 256

I tried adding /removing spaces after ':' still no luck 
my cassandra.yaml snippet

# Cassandra storage config YAML 

# NOTE:
#   See http://wiki.apache.org/cassandra/StorageConfiguration for
#   full explanations of configuration directives
# /NOTE

# The name of the cluster. This is mainly used to prevent machines in
# one logical cluster from joining another.
cluster_name:'Test Cluster'
# This defines the number of tokens randomly assigned to this node on the ring
# The more tokens, relative to other nodes, the larger the proportion of data
# that this node will store. You probably want all nodes to have the same number
# of tokens assuming they have equal hardware capability.
#
# If you leave this unspecified, Cassandra will use the default of 1 token for legacy compatibility,
# and will use the initial_token as described below.
#
# Specifying initial_token will override this setting on the node's initial start,
# on subsequent starts, this setting will apply even if initial token is set.
#
# If you already have a cluster with 1 token per node, and wish to migrate to
# multiple tokens per node

num_tokens : 256

# initial_token allows you to specify tokens manually.  While you can use # it with
# vnodes (num_tokens > 1, above) -- in which case you should provide a 
# comma-separated list -- it's primarily used when adding nodes # to legacy clusters 
# that do not have vnodes enabled.
# initial_token:

**Comment by lenindv** [comment]
my apologies did not notice the font :( my bad

**Comment by robbybb** [comment]
You really should document the limitation about a single data directory.  It was an unexpected limitation -- I wasted a fair amount of time finding this out for myself.

**Comment by rzvoncek** [comment]
@lenindv, I'm sorry, but I can't tell what's wrong with the yaml from just the snippet, even after formatting. In case you're still having the issue, I'd suggest first removing all the comments and then checking for any rouge non-printable special characters (like `\r`). 

@robbybb, I'm also sorry you lost time working this out. I've always thought it happens soon enough:
```
[2020-04-03 15:22:57,311] DEBUG: Loading configuration from medusa-example.ini
[2020-04-03 15:22:57,312] INFO: Monitoring provider is noop
[2020-04-03 15:22:57,333] DEBUG: This server has systemd: False
[2020-04-03 15:22:57,334] WARNING: is ccm : 0
[2020-04-03 15:22:57,354] ERROR: This error happened during the backup: Medusa only supports one data directory
```
Did you maybe hit some other code path where this tricked you?

One way or another, I've opened #104 to document this properly.
